//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericRPG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mechanics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mechanics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenericRPG.Properties.Mechanics", typeof(Mechanics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Game.
        /// </summary>
        internal static string Command_QuitGame {
            get {
                return ResourceManager.GetString("Command_QuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Level.
        /// </summary>
        internal static string Command_QuitLevel {
            get {
                return ResourceManager.GetString("Command_QuitLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        internal static string Command_StartGame {
            get {
                return ResourceManager.GetString("Command_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Next Level.
        /// </summary>
        internal static string Command_StartLevel {
            get {
                return ResourceManager.GetString("Command_StartLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.2.
        /// </summary>
        internal static string DefaultEnemies_BossMultiplier {
            get {
                return ResourceManager.GetString("DefaultEnemies_BossMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string DefaultEnemies_Fighter_Strength {
            get {
                return ResourceManager.GetString("DefaultEnemies_Fighter_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string DefaultEnemies_HitPoints_LowerLimit {
            get {
                return ResourceManager.GetString("DefaultEnemies_HitPoints_LowerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60.
        /// </summary>
        internal static string DefaultEnemies_HitPoints_UpperLimit {
            get {
                return ResourceManager.GetString("DefaultEnemies_HitPoints_UpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.2.
        /// </summary>
        internal static string DefaultEnemies_Mail_ArmorReduction {
            get {
                return ResourceManager.GetString("DefaultEnemies_Mail_ArmorReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string DefaultEnemies_SpellCaster_Mana {
            get {
                return ResourceManager.GetString("DefaultEnemies_SpellCaster_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string DefaultEnemies_Staff_LowerAttack {
            get {
                return ResourceManager.GetString("DefaultEnemies_Staff_LowerAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string DefaultEnemies_Staff_UpperAttack {
            get {
                return ResourceManager.GetString("DefaultEnemies_Staff_UpperAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string DefaultEnemies_Sword_LowerAttack {
            get {
                return ResourceManager.GetString("DefaultEnemies_Sword_LowerAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string DefaultEnemies_Sword_UpperAttack {
            get {
                return ResourceManager.GetString("DefaultEnemies_Sword_UpperAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Fighter_DefaultStrength {
            get {
                return ResourceManager.GetString("Fighter_DefaultStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string SpellCaster_DefaultMana {
            get {
                return ResourceManager.GetString("SpellCaster_DefaultMana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string SpellCaster_DefaultUnnarmedDamage {
            get {
                return ResourceManager.GetString("SpellCaster_DefaultUnnarmedDamage", resourceCulture);
            }
        }
    }
}
