//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericRPG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenericRPG.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack!.
        /// </summary>
        internal static string Command_Attack {
            get {
                return ResourceManager.GetString("Command_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flee! (shameful display).
        /// </summary>
        internal static string Command_Flee {
            get {
                return ResourceManager.GetString("Command_Flee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be executed due to the following reason: {1}. Please try again!.
        /// </summary>
        internal static string Command_GenericFailureMessage {
            get {
                return ResourceManager.GetString("Command_GenericFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was executed successfully. Result {1}.
        /// </summary>
        internal static string Command_GenericSuccessMessage {
            get {
                return ResourceManager.GetString("Command_GenericSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Selection Error: {0}.
        /// </summary>
        internal static string Command_InvalidCommand {
            get {
                return ResourceManager.GetString("Command_InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Game.
        /// </summary>
        internal static string Command_QuitGame {
            get {
                return ResourceManager.GetString("Command_QuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Level.
        /// </summary>
        internal static string Command_QuitLevel {
            get {
                return ResourceManager.GetString("Command_QuitLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         .
        /// </summary>
        internal static string Command_Separator {
            get {
                return ResourceManager.GetString("Command_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fight the next group of enemies!.
        /// </summary>
        internal static string Command_StartFight {
            get {
                return ResourceManager.GetString("Command_StartFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        internal static string Command_StartGame {
            get {
                return ResourceManager.GetString("Command_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Next Level.
        /// </summary>
        internal static string Command_StartLevel {
            get {
                return ResourceManager.GetString("Command_StartLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy Attacked Successfully..
        /// </summary>
        internal static string Command_SuccessResult_Attack {
            get {
                return ResourceManager.GetString("Command_SuccessResult_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flee Operation was successful..
        /// </summary>
        internal static string Command_SuccessResult_Flee {
            get {
                return ResourceManager.GetString("Command_SuccessResult_Flee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Quit..
        /// </summary>
        internal static string Command_SuccessResult_Quit {
            get {
                return ResourceManager.GetString("Command_SuccessResult_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Quit..
        /// </summary>
        internal static string Command_SuccessResult_QuitLevel {
            get {
                return ResourceManager.GetString("Command_SuccessResult_QuitLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Enemy Party was engaged..
        /// </summary>
        internal static string Command_SuccessResult_StartFight {
            get {
                return ResourceManager.GetString("Command_SuccessResult_StartFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Started..
        /// </summary>
        internal static string Command_SuccessResult_StartLevel {
            get {
                return ResourceManager.GetString("Command_SuccessResult_StartLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You ran away and left the group of enemies behind! You can rest before you engage them again. .
        /// </summary>
        internal static string Event_Flee {
            get {
                return ResourceManager.GetString("Event_Flee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.##.
        /// </summary>
        internal static string Formatting_StatsNumberFormatting {
            get {
                return ResourceManager.GetString("Formatting_StatsNumberFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was attacked by {1} for {2} {3} damage!.
        /// </summary>
        internal static string Menu_AttackedByTemplate {
            get {
                return ResourceManager.GetString("Menu_AttackedByTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} attacked {1} for {2} {3} damage!.
        /// </summary>
        internal static string Menu_AttackedTemplate {
            get {
                return ResourceManager.GetString("Menu_AttackedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose the enemy you would like to attack:.
        /// </summary>
        internal static string Menu_ChooseMobToAttack {
            get {
                return ResourceManager.GetString("Menu_ChooseMobToAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Menu_CommandsOnTheSameLine {
            get {
                return ResourceManager.GetString("Menu_CommandsOnTheSameLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select One of the following commands by replying with the corresponding number:.
        /// </summary>
        internal static string Menu_EligibleCommands {
            get {
                return ResourceManager.GetString("Menu_EligibleCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR HERO: {0}.
        /// </summary>
        internal static string Menu_HeroStatus {
            get {
                return ResourceManager.GetString("Menu_HeroStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently in combat with the following enemies:.
        /// </summary>
        internal static string Menu_InCombat {
            get {
                return ResourceManager.GetString("Menu_InCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}.
        /// </summary>
        internal static string Menu_ListDisplayTemplate {
            get {
                return ResourceManager.GetString("Menu_ListDisplayTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string Menu_MobDisplayTemplate {
            get {
                return ResourceManager.GetString("Menu_MobDisplayTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no! Your hero is slain! With the death of this character the thread of prophecy is severed!!!!.
        /// </summary>
        internal static string Menu_PlayerLost {
            get {
                return ResourceManager.GetString("Menu_PlayerLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re sorry to see you go! We hope you enjoyed our game!.
        /// </summary>
        internal static string Menu_PlayerQuit {
            get {
                return ResourceManager.GetString("Menu_PlayerQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! No more Levels! You won the game!.
        /// </summary>
        internal static string Menu_PlayerWon {
            get {
                return ResourceManager.GetString("Menu_PlayerWon", resourceCulture);
            }
        }
    }
}
